### ISSUE TITLE
Documentation and usage

### ISSUE THREAD

**Issue by TheRealOwenRees** [sam-19/chess.ts#1]
Please excuse the slight abuse of the issues feature.

Could you possibly tell me how much of the original documentation is still valid from the parent of these forks?
[chess.js](https://github.com/jhlywa/chess.js)

I would very much like to include this in an upcoming project that I am planning, especially as it is a maintained version of aaronfi's excellent fork that included variations.

If I do get round to using it, would you also mind if I deconstructed the original readme file to reflect this new repo?

Thank you in advance, and I hope you are having a pleasant holiday period.

**Comment by sam-19** [comment]
Hi, Owen, and thank you for your interest in my project!

I'm afraid very little to none of the original chess.js documentation applies to this project. Very little of even the base project, aaronfi's chess-es6, remain and this could be considered an almost complete rewrite of it.

I must admit that I have been neglecting this library lately. I have a bit of free time before New year, so I'll try to write some basic documentation and extend the tests for this project.

Usually my project licensing is more lenient, but for this one I was forced to use GPL-3 due to the parent project license. You are free to use this project in any way the license permits. Happy holidays to you too!

**Comment by TheRealOwenRees** [comment]
Thank you for your reply.

I have a stack of other projects to finish up before I get round to this, so there is no rush at all, and please don't do it just for me!

I am now watching this repo with 'all activity' just in case there are changes in the near future.

I wish you all the best for 2023
